## Feature Engineering for Instagram Data

List of features:
- Cumulative Number of Posts as of Post Created (n_cumpost)
- Number of Posts in Past 6/3/1 Months (n_postsP6M, n_postsP3M, n_postsP1M) (to revisit) -> ave variance % of followers
- Number of Days Since Last Posted (d_lastpost)
- Number of Days since First posted (d_firstpost)

### 0. Data Load

In [12]:
import sqlalchemy 
import pymysql
import pandas as pd
import numpy as np

In [2]:
# Connection details
user = "admin"
password = "tuIzaqrAKLMe32G0"
host = "instagram-data-db.csik1hfjt1qb.us-east-1.rds.amazonaws.com"
port = 3306
db = "instagram_data"
connection_engine = sqlalchemy.create_engine('mysql+pymysql://' + user + ':' + password + '@' + host + ':' + str(port) + '/' + db , echo=True)
# You can use user, password, port and db info to connect via MySQL Workbench

In [3]:
# Write your SQL through this way in Python (returns a Pandas dataframe)
data = pd.read_sql('select * from ins_account_data',con=connection_engine)

2022-04-06 05:15:11,991 INFO sqlalchemy.engine.Engine SHOW VARIABLES LIKE 'sql_mode'
2022-04-06 05:15:11,993 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-04-06 05:15:12,131 INFO sqlalchemy.engine.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2022-04-06 05:15:12,134 INFO sqlalchemy.engine.Engine [generated in 0.00259s] {}
2022-04-06 05:15:12,176 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2022-04-06 05:15:12,178 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-04-06 05:15:12,257 INFO sqlalchemy.engine.Engine SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2022-04-06 05:15:12,260 INFO sqlalchemy.engine.Engine [generated in 0.00255s] {'table_schema': 'instagram_data', 'table_name': 'select * from ins_account_data'}
2022-04-06 05:15:12,313 INFO sqlalchemy.engine.Engine select * from ins_account_data
2022-04-06 05:15:12,315 INFO sqlalchemy.engine.Engine [raw sql] {}

In [4]:
data

,index,Account,User Name,Followers at Posting,Post Created,Type,Total Interactions,Likes,Comments,Views,...,is_linked,Description_sentiment,Description_subjective,Description_len,Image_Text_len,account_effect,Type_cate,Description_sentiment_score,Description_subjective_score,cvfold
0,0,Rebecca Ferguson,officialrebeccaferguson,404268.0,2021-10-17 13:29:58,Album,104703,104238,465,0,...,1,Negative,Objective,76,0.0,297234.538462,0,0.000000,0.000000,train
1,1,Rebecca Ferguson,officialrebeccaferguson,490753.0,2021-11-15 11:42:52,Album,102836,102426,410,0,...,1,Negative,Objective,150,0.0,297234.538462,0,0.000000,0.500000,train
2,2,Rebecca Ferguson,officialrebeccaferguson,472941.0,2021-11-04 17:52:59,Photo,101672,101230,442,0,...,1,Negative,Objective,34,0.0,297234.538462,1,0.000000,0.000000,train
3,3,Rebecca Ferguson,officialrebeccaferguson,333044.0,2021-08-06 16:40:38,Photo,99049,97849,1200,0,...,1,Positive,Subjective,141,0.0,297234.538462,1,0.700000,0.900000,train
4,4,Rebecca Ferguson,officialrebeccaferguson,533227.0,2021-12-31 15:39:14,Album,98218,97230,988,0,...,1,Positive,Subjective,85,0.0,297234.538462,0,0.350000,0.694444,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256135,256135,Travel Blogger Revati Charles,differentdoors,29898.0,2019-08-04 01:10:06,Photo,747,738,9,0,...,1,Positive,Subjective,1150,0.0,22904.099822,1,0.216667,0.533333,train
256136,256136,marcvetri,marcvetri,39603.0,2017-08-25 18:56:00,Photo,747,729,18,0,...,1,Positive,Objective,109,0.0,59085.961818,1,0.200000,0.400000,train
256137,256137,Max Eli,thesussmans,12670.0,2019-03-28 10:21:22,Photo,747,731,16,0,...,1,Positive,Objective,1877,0.0,21546.686441,1,0.143200,0.437698,train
256138,256138,Kit Lee,itskitlee,44012.0,2017-11-25 08:52:37,Photo,747,734,13,0,...,1,Positive,Objective,1002,0.0,36941.444277,1,0.029870,0.439177,train
256139,256139,Quincy Acy,quincyacy,65621.0,2017-08-12 15:41:59,Photo,746,738,8,0,...,1,Positive,Subjective,72,0.0,60468.053628,1,0.366667,0.566667,train

### 1. Compute Cumulative Number of Posts as of Post Created (n_cumpost)

In [5]:
# sort by username and post creation
df = data.sort_values(by=['User Name','Post Created'], ascending=True)
df = df.reset_index(drop=True)

# count from 1 for each username
df['n_cumpost'] = df.groupby(['User Name']).cumcount() + 1
df.loc[df['User Name'] == 'chelseaspack']

,index,Account,User Name,Followers at Posting,Post Created,Type,Total Interactions,Likes,Comments,Views,...,Description_sentiment,Description_subjective,Description_len,Image_Text_len,account_effect,Type_cate,Description_sentiment_score,Description_subjective_score,cvfold,n_cumpost
52942,252932,Chelsea Spack,chelseaspack,2086.0,2015-08-06 19:03:32,Photo,761,752,9,0,...,Positive,Subjective,92,0.0,24562.225225,1,0.500,0.600,test,1
52943,50971,Chelsea Spack,chelseaspack,2095.0,2015-08-09 22:33:36,Photo,2289,2222,67,0,...,Positive,Objective,126,0.0,24562.225225,1,0.300,0.200,test,2
52944,193471,Chelsea Spack,chelseaspack,2683.0,2015-10-12 19:51:16,Photo,969,938,31,0,...,Positive,Objective,108,0.0,24562.225225,1,0.200,0.500,train,3
52945,238242,Chelsea Spack,chelseaspack,3133.0,2015-10-18 14:48:24,Photo,806,796,10,0,...,Negative,Objective,152,0.0,24562.225225,1,0.000,0.000,test,4
52946,152857,Chelsea Spack,chelseaspack,3410.0,2015-10-19 18:55:22,Photo,1162,1150,12,0,...,Negative,Objective,76,0.0,24562.225225,1,0.000,0.000,train,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53270,208008,Chelsea Spack,chelseaspack,26705.0,2021-08-29 23:45:23,Photo,911,867,44,0,...,Negative,Objective,4,0.0,24562.225225,1,0.000,0.000,train,329
53271,255634,Chelsea Spack,chelseaspack,26619.0,2021-10-10 16:29:39,Album,753,739,14,0,...,Positive,Subjective,76,0.0,24562.225225,0,0.500,0.750,train,330
53272,246635,Chelsea Spack,chelseaspack,26488.0,2021-12-10 02:27:06,Album,780,766,14,0,...,Positive,Subjective,71,0.0,24562.225225,0,0.500,1.000,test,331
53273,190360,Chelsea Spack,chelseaspack,26463.0,2021-12-14 13:36:49,Photo,982,946,36,0,...,Positive,Subjective,137,0.0,24562.225225,1,0.325,0.600,test,332
53274,252574,Chelsea Spack,chelseaspack,26434.0,2021-12-19 15:02:56,Album,762,746,16,0,...,Positive,Subjective,108,0.0,24562.225225,0,0.525,0.525,train,333

### 2. Number of Posts in Past 6/3/1 Months (n_postsP6M, n_postsP3M, n_postsP1M)

### 3. Compute Number of Days Since Last Posted (d_lastpost)

In [6]:
# indicate 1 for first post
df['first_post'] = np.where(df['n_cumpost']==1, 1, 0)

In [7]:
# compute date diff from last post
df['d_lastpost'] = df.groupby('User Name')['Post Created'].diff().apply(lambda x: x.days)
df.loc[df['User Name'] == 'chelseaspack']

,index,Account,User Name,Followers at Posting,Post Created,Type,Total Interactions,Likes,Comments,Views,...,Description_len,Image_Text_len,account_effect,Type_cate,Description_sentiment_score,Description_subjective_score,cvfold,n_cumpost,first_post,d_lastpost
52942,252932,Chelsea Spack,chelseaspack,2086.0,2015-08-06 19:03:32,Photo,761,752,9,0,...,92,0.0,24562.225225,1,0.500,0.600,test,1,1,NaN
52943,50971,Chelsea Spack,chelseaspack,2095.0,2015-08-09 22:33:36,Photo,2289,2222,67,0,...,126,0.0,24562.225225,1,0.300,0.200,test,2,0,3.0
52944,193471,Chelsea Spack,chelseaspack,2683.0,2015-10-12 19:51:16,Photo,969,938,31,0,...,108,0.0,24562.225225,1,0.200,0.500,train,3,0,63.0
52945,238242,Chelsea Spack,chelseaspack,3133.0,2015-10-18 14:48:24,Photo,806,796,10,0,...,152,0.0,24562.225225,1,0.000,0.000,test,4,0,5.0
52946,152857,Chelsea Spack,chelseaspack,3410.0,2015-10-19 18:55:22,Photo,1162,1150,12,0,...,76,0.0,24562.225225,1,0.000,0.000,train,5,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53270,208008,Chelsea Spack,chelseaspack,26705.0,2021-08-29 23:45:23,Photo,911,867,44,0,...,4,0.0,24562.225225,1,0.000,0.000,train,329,0,3.0
53271,255634,Chelsea Spack,chelseaspack,26619.0,2021-10-10 16:29:39,Album,753,739,14,0,...,76,0.0,24562.225225,0,0.500,0.750,train,330,0,41.0
53272,246635,Chelsea Spack,chelseaspack,26488.0,2021-12-10 02:27:06,Album,780,766,14,0,...,71,0.0,24562.225225,0,0.500,1.000,test,331,0,60.0
53273,190360,Chelsea Spack,chelseaspack,26463.0,2021-12-14 13:36:49,Photo,982,946,36,0,...,137,0.0,24562.225225,1,0.325,0.600,test,332,0,4.0
53274,252574,Chelsea Spack,chelseaspack,26434.0,2021-12-19 15:02:56,Album,762,746,16,0,...,108,0.0,24562.225225,0,0.525,0.525,train,333,0,5.0

### 4. Compute Number of Days since First posted (d_firstpost)

In [8]:
# take days since last posted
df['d_firstpost'] = df['d_lastpost']

# accumulate days since last posted for each username
df.loc[:, 'd_firstpost'] = df.groupby(['User Name', 'first_post'])['d_firstpost'].cumsum()
df.loc[df['User Name'] == 'chelseaspack']

,index,Account,User Name,Followers at Posting,Post Created,Type,Total Interactions,Likes,Comments,Views,...,Image_Text_len,account_effect,Type_cate,Description_sentiment_score,Description_subjective_score,cvfold,n_cumpost,first_post,d_lastpost,d_firstpost
52942,252932,Chelsea Spack,chelseaspack,2086.0,2015-08-06 19:03:32,Photo,761,752,9,0,...,0.0,24562.225225,1,0.500,0.600,test,1,1,NaN,NaN
52943,50971,Chelsea Spack,chelseaspack,2095.0,2015-08-09 22:33:36,Photo,2289,2222,67,0,...,0.0,24562.225225,1,0.300,0.200,test,2,0,3.0,3.0
52944,193471,Chelsea Spack,chelseaspack,2683.0,2015-10-12 19:51:16,Photo,969,938,31,0,...,0.0,24562.225225,1,0.200,0.500,train,3,0,63.0,66.0
52945,238242,Chelsea Spack,chelseaspack,3133.0,2015-10-18 14:48:24,Photo,806,796,10,0,...,0.0,24562.225225,1,0.000,0.000,test,4,0,5.0,71.0
52946,152857,Chelsea Spack,chelseaspack,3410.0,2015-10-19 18:55:22,Photo,1162,1150,12,0,...,0.0,24562.225225,1,0.000,0.000,train,5,0,1.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53270,208008,Chelsea Spack,chelseaspack,26705.0,2021-08-29 23:45:23,Photo,911,867,44,0,...,0.0,24562.225225,1,0.000,0.000,train,329,0,3.0,2065.0
53271,255634,Chelsea Spack,chelseaspack,26619.0,2021-10-10 16:29:39,Album,753,739,14,0,...,0.0,24562.225225,0,0.500,0.750,train,330,0,41.0,2106.0
53272,246635,Chelsea Spack,chelseaspack,26488.0,2021-12-10 02:27:06,Album,780,766,14,0,...,0.0,24562.225225,0,0.500,1.000,test,331,0,60.0,2166.0
53273,190360,Chelsea Spack,chelseaspack,26463.0,2021-12-14 13:36:49,Photo,982,946,36,0,...,0.0,24562.225225,1,0.325,0.600,test,332,0,4.0,2170.0
53274,252574,Chelsea Spack,chelseaspack,26434.0,2021-12-19 15:02:56,Album,762,746,16,0,...,0.0,24562.225225,0,0.525,0.525,train,333,0,5.0,2175.0

### 5. Summerize User Profiles

In [9]:
# count number of user accounts
user_list = []
user_list = pd.unique(df['User Name']).tolist()
len(user_list)

1272

In [10]:
user_list

['35_fitz',
 '703richard',
 '77flippedofficial',
 '80miles',
 '8nicknovak',
 '98chrissmith',
 '_elling10',
 '_godj_',
 '_one8_',
 '_slickrick',
 '_tim_barry_',
 'aarbeloa17',
 'aaron_ashmore',
 'aaronastanford',
 'aaronchase',
 'abbottcampaign',
 'abbrecadabra',
 'abbytegnelia',
 'abbywilde',
 'abethea41',
 'abigailklein_',
 'achando',
 'actordouglastait',
 'actressjessicacameron',
 'adammoryto',
 'adamottavino',
 'adamrbeach',
 'addisonzawada',
 'adelia_rasya',
 'adesuryaakbarr',
 'adhirkalyan',
 'adiasings',
 'adityarino_',
 'adreian_payne',
 'adrianacernanova',
 'adriandhy',
 'adrianhamias',
 'aellington38',
 'afro_thunder80',
 'agnesbruckner1',
 'agreatbigworld',
 'ahnaoreilly',
 'aimee_p_r',
 'aimeemullins',
 'aiysha_hart',
 'ajjtheband',
 'ajklein47',
 'ajwilliams23',
 'akselhennie',
 'alan_thicke',
 'alanpowell10',
 'albertfakdawer',
 'alcazarofficial',
 'alecmapa',
 'alekspaun',
 'alessiatrost',
 'alexabbad',
 'alexagoddard',
 'alexanderkarim',
 'alexanderwraith',
 'alexgetink',
 'alexinwanderland',
 'alexiskrauss',
 'alexkrosney',
 'alexlen_25',
 'alexokafor',
 'alice_tate',
 'alicearutkin',
 'aliceevansgruff',
 'alicewetterlund',
 'alicia_coppola',
 'aliciaziegler',
 'alilandry',
 'alimensan',
 'alison.e.wood',
 'alison_goldfrapp',
 'alisonarngrim',
 'alisonkrauss',
 'aliyahobrien',
 'allahlas',
 'allanhawco',
 'allanhyde',
 'allankingdom',
 'allison_tolman',
 'allisonmcateeofficial',
 'allisonsmithart',
 'allthemwitchesband',
 'alphabeat',
 'amandabananaxx',
 'amandaselabeauty',
 'americanaquarium',
 'americanauthors',
 'amlameenbaby',
 'amoultrie',
 'amuiseme',
 'amy_sall',
 'amychmelecki',
 'amygumenick',
 'amywinehousethebest',
 'anagasteyer',
 'andhim_music',
 'andrea_faustini',
 'andreabogart',
 'andrewbayer',
 'andrewfreund',
 'andylevitre',
 'angelatrimbur',
 'angeliquecabral',
 'angieaway',
 'animalvinny',
 'annabeth_gish',
 'annapopplewellreal',
 'annawoodyall',
 'anncurry',
 'annecatherinefrey',
 'anneheche',
 'annetmahendru',
 'anthonycedwards',
 'anthonykonechny',
 'antonthelander',
 'anyadwinov',
 'apolloniamusic',
 'aqshipley',
 'arielletgold',
 'arishapiro',
 'arlenescarpeta',
 'artj97',
 'asgeirmusic',
 'ashleigh_cummings',
 'ashley_hinshaw',
 'ashleyfiolek_67',
 'ashlynn_yennie',
 'ashperson',
 'asnantips',
 'athornton14',
 'athousandhorses',
 'atlasgenius',
 'atolliver44',
 'atv1ucla',
 'aubriepick',
 'audreyjustinetautou',
 'auroraperrineau',
 'austinfalk',
 'autumnshields3',
 'avaacres',
 'axel.andaviar',
 'aylak',
 'aylukechristopher',
 'azitagram',
 'b_wegher',
 'babyshamblesuk',
 'backpackingmatt',
 'badsuns',
 'baileynoble11',
 'bakermatmusic',
 'baltgetty',
 'bandofheathens',
 'baratampubolon',
 'barbaracrampton',
 'barbaramoore10',
 'barbaraniven',
 'barekiwi',
 'barenakedladiesmusic',
 'bartpumpkin',
 'bbosker',
 'bbwolf94',
 'bcoyle50',
 'bearhandsband',
 'beautyamazonmua',
 'beautybycassie93',
 'beddu17',
 'beemerpga',
 'bellesglasgow',
 'bemby_putuanda',
 'ben_ferguson',
 'bencranegolf',
 'benemayr',
 'bengleib',
 'bennybookmarks',
 'benrichardson',
 'benvereen',
 'berndwiesberger',
 'bestahmed',
 'bethorton',
 'bethriesgraf',
 'bflowers24',
 'bgrimey_21',
 'bigbake92',
 'bigbruh70',
 'bigdatabigdata',
 'bigjoe',
 'billyjackbrawner',
 'bipolaire61',
 'bishopsankey',
 'bixelboys',
 'bkindler',
 'blackpistolfire',
 'blanckmass',
 'blawrie1515',
 'blindmelonband',
 'blogtasteaway',
 'blroberts22',
 'bluestraveler',
 'blvckfawn',
 'bmccarthy32',
 'bobbyjsph',
 'bodhielfman',
 'bogie10',
 'bolive32',
 'bossagurl',
 'boyandbear',
 'bradfordcox',
 'bradneely',
 'branderoderick',
 'brandon_quintin_adams',
 'brandonlinder65',
 'breagrant',
 'brendankjmeyer',
 'brendon',
 'brenfosterreal',
 'brentcelek',
 'bret_lockett',
 'brettanderson25',
 'brettkern6',
 'brettrat',
 'brianhartline',
 'briankgrubb',
 'briannabrownkeen',
 'brianstelter',
 'bridechilla',
 'brigaheelan',
 'brinakins',
 'brittaudreyallen',
 'brockcrouch',
 'brockjpierce',
 'brockvkelly',
 'brodieharper',
 'brokenbells',
 'broodsmusic',
 'brookielyons',
 'brooklynsudano',
 'brooksreed50',
 'bryan_batt',
 'bryanbubbly',
 'budgettraveller',
 'busterskrine',
 'butchwalker',
 'bwalt19',
 'bweeden3',
 'c.upshaw_91',
 'c.williams26',
 'c__robertson53',
 'caitcarv',
 'caitlin.gerard',
 'calbowilson',
 'calebruminer',
 'camdstew',
 'camillebecerra',
 'camrich11',
 'canvasoflight',
 'captain_41',
 'captain_rowe',
 'carlcraignet',
 'carlyfries18',
 'carolynhennesy',
 'carriestevensxo',
 'casekeenum7',
 'cat_vas_hawkins',
 'catherinehardwicke',
 'catsteadman',
 'cestchristine',
 'chaoschaosband',
 'chaoticsymphony',
 'charlesbradley',
 'charli_robinson',
 'charliebakerma',
 'chase_daniel',
 'chastyballesteros',
 'chef_rouge',
 'chefangusan',
 'chefbangerter',
 'chefbohati',
 'chefchuckhughes',
 'chefdannysmiles',
 'chefsawyer',
 'chelseagilligan',
 'chelsearendon',
 'chelseaspack',
 'chelseaxhobbs',
 'chiaradimeoo',
 'chicagolunch',
 'china_chow',
 'chitra',
 'chriscanty99',
 'chrischristie',
 'chrisloho',
 'chrismassoglia',
 'chrismike33',
 'chrisriggi',
 'chrissandersart',
 'christianantidormi',
 'christianmarc',
 'christinawinkelmann',
 'christinawren',
 'chrysteepharris',
 'cindyambuehl',
 'circawaves',
 'cjgeorgia99',
 'cjspiller28',
 'cjwilsonphoto',
 'claudialeelive',
 'cleomassey',
 'cleopatracoleman',
 'cliveowenofficial',
 'clkstar',
 'coastsband',
 'cobybellagram',
 'cocozurita',
 'codyckennedy',
 'colea45',
 'colebuck58',
 'colincabalka',
 'colinmontgomerie',
 'comedianjohnheffron',
 'conniedesousa',
 'connienielsenofficial',
 'connorprice_',
 'cookiesncandies',
 'coolduder',
 'coreydickerson',
 'coreypaulmusic',
 'cotedeperff',
 'cozizuehlsdorff',
 'craigyferg',
 'crisurena',
 'cullyinthehouse',
 'curtiskeene',
 'cwgeere',
 'cwrankin',
 'd1mo',
 'd9xgza',
 'd_jennings_tb8',
 'da_king_son18',
 'dagienkz',
 'dallas.pratama',
 'dallasfriday',
 'damarisaguiar',
 'damiankulash',
 'danamboyer',
 'danbaileyfive',
 'dangergirlred',
 'dangerousbiz',
 'danielabobadilla',
 'danielcudmore',
 'danieldescalso',
 'danielespinozuh',
 'daniellanois',
 'danielleguldin',
 'dankilgore',
 'danlayus',
 'daphnezuniga',
 'daronrahlves',
 'darrenhayes',
 'darrenlegallo',
 'datruthonduty',
 'davidamerson1',
 'davidfaustino',
 'davidgray',
 'davidnelson86',
 'davidwalton',
 'dawnaleeheising',
 'dawnolivieri',
 'dbacksbaxter',
 'dcolturi',
 'dean_ogorman',
 'deaundrebonds',
 'deeohgee__',
 'deepdish',
 'deidrehall_official',
 'dejuan45',
 'delicatesteve',
 'deltaspirit',
 'denardx',
 'dennisadishwara',
 'denoodle',
 'deobia.oparei',
 'deon_richmond',
 'dfells85',
 'dgbeckham18',
 'dianeneal',
 'dianesawyer',
 'diarrheaplanet',
 'diesel_music',
 'differentdoors',
 'dillongee35',
 'dilshadvadsaria',
 'dinameyer',
 'dirtymikedowdy',
 'dizmihok',
 'djsimonpatterson',
 'dlamarc33',
 'doktadil',
 'domhnall.gleeson',
 'dominicdeutscher',
 'domrains',
 'donnyalamsyah',
 'dontforget2move',
 'dontworryitssheila',
 'dougducey',
 'dpowtermusic',
 'drdogmusic',
 'drerob',
 'drew_roy',
 'drewbutler',
 'drewkelly',
 'drewpomeranz',
 'dsolano17',
 'durelleskridge37',
 'dustinmain',
 'duzer',
 'dw34',
 'dwierbrown',
 'dwpbbq',
 'dylanthebruce',
 'e_kaspersky',
 'eamonofficial',
 'earlmitchell90',
 'earthxplorer',
 'easygolding',
 'eddickson84',
 'eddieroyalwr',
 'eddiesteeples',
 'edharcourt',
 'ediblebrooklyn',
 'edibleliving',
 'editorsofficial',
 'edwinafindley',
 'egranero11',
 'ehle_jennifer',
 'ekaterinazalitko',
 'ekeberlee',
 'elainedances',
 'elbravo_47',
 'eldusty',
 'elenakampouris',
 'eliasjmharris',
 'elimizrahi',
 'elisabethtnt',
 'elizabethreaser',
 'ellewongster',
 'elliphantmusic',
 'elmatatan196',
 'elultimovecino',
 'elvisnasco',
 'elyse_levesque',
 'emanueladepaula',
 'emaynor3',
 'emilieautumnofficial',
 'emily1loverios',
 'emilydougherty',
 'emilyjtennant',
 'emmabell',
 'emmalalonde1',
 'emmanuellevaugier',
 'emortimer',
 'emziculz',
 'en_hakim',
 'encebagus_',
 'enriquemurciano',
 'eprombeats',
 'erasureinfo',
 'ericdjordan',
 'erichbergen',
 'erichutchinson',
 'erickush64',
 'ericrclose',
 'erikparkerstudio',
 'erinbethea',
 'erinkarpluk',
 'erinlcummings',
 'erniehalter',
 'erolalkan',
 'esmzeros',
 'esta',
 'estella_warren',
 'ethanembry',
 'eugenesnaps',
 'evangeiselman',
 'evansanders_spt',
 'eve_mauro',
 'eveharlow',
 'ezraklein',
 'faimfatale',
 'falcons',
 'farmert',
 'farrellgram',
 'farrfrencheska',
 'fashawn',
 'faustinathefuzz',
 'fauvecorp',
 'feistmusic',
 'fencesmusic',
 'ferbaronne',
 'ficklefriends',
 'finkmusic',
 'fionaappleig',
 'fitzandthetantrums',
 'flintstagram77',
 'florabaker',
 'flowenchy',
 'flyleafmusic',
 'foglersfictions',
 'followblakecooper',
 'fortebowie',
 'fortromeau',
 'foyeboy',
 'frankieshaw',
 'franklinelectric',
 'frankoceanitaly',
 'fred22jackson',
 'freddyrodriguezofficial',
 'futurebirds',
 'g_bernard_xxv',
 'gabriel.villaran',
 'gabrielleanwar',
 'gaiastreetart',
 'gaiuscharles',
 'galaelf',
 'galmekel',
 'garrettegraham',
 'garrettrwang',
 'garry_norris',
 'garynuman',
 'gaslampkiller',
 'gatlinkatejames',
 'gavinkaysen',
 'gcoetzeegolf',
 'gemitasamarra',
 'genevieveangelson',
 'genevievebue',
 'gengahr',
 'genosacks',
 'geoffogilvy',
 'geoffreyarend',
 'geographermusic',
 'george_iloka',
 'georgiamayking',
 'gethardshow',
 'gethinanthony',
 'gianniabroad',
 'gijsblom',
 'gillianzinser',
 'ginblossomsaz',
 'glambarbiie',
 'glamourbyyani',
 'glenn_dorsey',
 'goldroom',
 'gomikeg',
 'goodisness',
 'goudelock0',
 'governorbullock',
 'govinslee',
 'govmikehuckabee',
 'gracenotejam',
 'grant_wahl',
 'greatgoodfineok',
 'green_global_travel',
 'greglaswell',
 'gretagasparian',
 'grete.ski',
 'grrrltraveler',
 'gstephanopoulos',
 'guantanamobaywatch',
 'gustavoyacaman',
 'guster',
 'guychosuave',
 'haertsmusic',
 'hairbychristiaan',
 'halfwayanywhere',
 'hamzo55',
 'hanktime85',
 'harris_english',
 'hawk_inc',
 'hdubb215',
 'heatbeatmusic',
 'heathernova',
 'heemsworth',
 'heidydelarosa',
 'hepostsclouds',
 'hermioneolivia',
 'hindizahraofficial',
 'hitman37_',
 'hollisbrown',
 'hooverphonicoff',
 'houndmouth',
 'howiekday',
 'hpitocco',
 'hump',
 'huntarmusic',
 'iam_jamesyoung',
 'iam_jerryhughesjr',
 'iamdeeford',
 'iamjonguerra',
 'iamkenjonbarner',
 'iconforhire',
 'igetgwop',
 'ikangfawzi',
 'immallorybrooke',
 'inayaday',
 'insta_graham23',
 'instaarsenal2.0',
 'ironandwinetour',
 'iskak_gary',
 'itisnathaniel',
 'itscoachwhite23',
 'itseyjr',
 'itskitlee',
 'itsmako',
 'itsworthashot',
 'ivannathaniel',
 'ivylevan',
 'j.melo4',
 'j1flight',
 'j_bushrod7475',
 'j_crawford58',
 'j_hill_47',
 'ja_sniper7',
 'jab56',
 'jabaalsheard',
 'jack.vidgen',
 'jackmaster',
 'jadande',
 'jadealbany',
 'jaidelizabeth',
 'jamesmorrisonok',
 'jamesransom_nyc',
 'jamestownrevival',
 'jamiedurie',
 'jasonstix',
 'javyguerra54',
 'jaywright17',
 'jbanks_27',
 'jbdale72',
 'jbet26',
 'jcs_steeelow',
 'jeanholysmithereens',
 'jeanmarcskate',
 'jebbush',
 'jeffallen71',
 'jeffwithey',
 'jenkins6',
 'jenngrantmusic',
 'jenniferyoungstudio',
 'jennlouis',
 'jennydeluxe',
 'jenyeepastry',
 'jeremy_charles77',
 'jerrellfreeman50',
 'jessemthomas',
 'jforsett',
 'jimcramer',
 'jj_xxv',
 'jjwilcox_19',
 'jmayberry15',
 'joannebchang',
 'joekennedyiii',
 'joemande',
 'john_talabot',
 'johnaxford',
 'johnbuck44',
 'johnhickenlooper',
 'johnkasich',
 'johnkingcnn',
 'johnwilliamsonmusic',
 'joiquernaut',
 'jondevore',
 'jonleuer30',
 'jonnylangband',
 'jordanorwood',
 'jose.gonz.music',
 'joseph_arthur',
 'journeywonders',
 'jovitbaldivino',
 'joy__williams',
 'joyann_king',
 'joycemanorofficial',
 'joywave',
 'jroddywalston',
 'jsmarisnick',
 'jspithill',
 'jt3',
 'juicemayo3',
 'jujuchangabc',
 'jukeboxtheghost',
 'juliancohen11',
 'juliannazobrist',
 'julissa_andara',
 'julius_thomas',
 'jus_showoff',
 'justderaj',
 'justicecrewofficial',
 'justinpugh67',
 'justintownesearle',
 'justtravelous',
 'k8hardball',
 'k_dub01',
 'kaiserchiefs',
 'kandacesprings',
 'karaswisher',
 'karel_hanika',
 'karengnails',
 'karimichelleyoung',
 'kariseedenmusic',
 'kaseychambersmusic',
 'katebolduan',
 'katepeckme',
 'katiemeluaofficial',
 'katjapresnal',
 'katsia_d',
 'kdlang',
 'kebmomusic',
 'keirsimmons',
 'kellyframel',
 'kelvin.beachum.jr',
 'kendallnorman',
 'kenkaminesky',
 'kennybritt18',
 'kentonduty',
 'kenyonmartinsr',
 'kerrypieri',
 'kevin.minter',
 'kevintway',
 'keysnkrates',
 'kimnicky',
 'kingcharlesuk',
 'kingchip',
 'kingwalt6',
 'kirbychambliss',
 'kissmyconverse82',
 'kithoover',
 'kittentheband',
 'kittyflanagan',
 'kittythefool',
 'kk_mr99',
 'klingandemusic',
 'konjames10',
 'kris_allen',
 'kristaayne',
 'kristiedash',
 'krobbmx',
 'kt7',
 'kttunstall',
 'kurage_time',
 'kurleebelle',
 'lacktraviata',
 'laleh',
 'lamarrwoodley',
 'lancemoore16',
 'landlopers',
 'landry2fields',
 'lapaluxmusic',
 'larryhogan',
 'laschicasdelcan',
 'laurel_robbins',
 'laurentphilippon',
 'lauriesegall',
 'lauriesimmons',
 'lawrencerothman',
 'lawsonreeves91',
 'laylasubritzky',
 'leahtravels',
 'leedewyzeofficial',
 'leekernaghan',
 'leeranaldo',
 'legalnomads',
 'leighbirdnash',
 'lepostcard',
 'lesambruno',
 'liarsliarsliars',
 'liezelgarcia',
 'lilmade21',
 'lilycole',
 'lindi_ortega',
 'lisaloeb',
 'lnixon9',
 'localnatives',
 'lomogram',
 'los_lonely_boys',
 'losrakas',
 'lostncheeseland',
 'louievito',
 'lovethywalrus',
 'lowerdens',
 'lozula',
 'lucasbjerregaard',
 'lucinda_williams',
 'luclagasquie',
 'lunchiebaby',
 'luvgrzer',
 'luxurytraveldiary',
 'lyle_lovett',
 'lyndon',
 'magdalena_jasek',
 'mahaliabarnes',
 'maisonpublique',
 'makeupbymiiiso',
 'makeupbymila',
 'maldonadoiseverywhere',
 'mallardcottagechef',
 'mallory_jansen',
 'malloryontravel',
 'mamsorrow',
 'manoukbob',
 'marc_abaya',
 'marcelloarrambideenglish',
 'marcobaileyofficial',
 'marcvetri',
 'marianhillmusic',
 'mariannehope',
 'marionravn',
 'mariposamakeup',
 'mark_sanchez',
 'markberetta',
 'marketa_red',
 'markherzlich',
 'markmargulies',
 'marksixma',
 'marlisamusic',
 'marmozets',
 'marshon_brooks',
 'martabega',
 'martinbuttrich',
 'martinomalley',
 'masbutet',
 'mastersounds',
 'mattandkim',
 'mattbarkley',
 'mattcostamusic',
 'mattjnovak',
 'mattnathanson',
 'maxfrost',
 'maximhabanec',
 'mayerhawthorne',
 'mayorrahm',
 'mazzystar4ever',
 'mbrockers90',
 'mcd4nny',
 'mcginnessworks',
 'mcuddy5_3_23',
 'meaganethell',
 'megmac',
 'megsmakeupxo',
 'melissatkautz',
 'merrickwatts',
 'mez.heirs',
 'mgilchr',
 'michaeljspear',
 'michelle_elie',
 'mickyb273',
 'mightykingjenkins',
 'miguelinciarte',
 'mike_doughty_',
 'mikediamond',
 'mikefloyd',
 'mikeglennon8',
 'mikegriff33',
 'mikeiupati76',
 'mikemo17',
 'mileenaprows',
 'milogreene',
 'miss_moss',
 'missbettyrose',
 'mister_krisp',
 'misterwives',
 'moe_harkless',
 'monicamartin',
 'monicawangphoto',
 'montecristo_ritchie',
 'moonstar88band',
 'morgancox46',
 'moristeele',
 'mrhyde_24',
 'mrjoshhopkins',
 'mrpauer',
 'mrslanglam',
 'mrtbjorn',
 'mtrumbo44',
 'mwacha52',
 'mysteryjets',
 'nailer1064',
 'nailjob',
 'nancydbrown',
 'nanettelepore',
 'nariman.rastegar',
 'nataliekarpushenko',
 'natalieprass',
 'nathanbarnatt',
 'nathanfoleyofficial',
 'nefootsteps',
 'neilfinnofficial',
 'nekocaseofficial',
 'neonhitch',
 'newpoliticsmusic',
 'nicholaf44',
 'nicholascollison',
 'nick2oon',
 'nickelcreek',
 'nickfolk2',
 'nicolascolsaerts',
 'nihilisten',
 'niiarocco',
 'nikbaden',
 'nikiaphoenix',
 'nikkiogun',
 'ninetwotimes',
 'ninety1',
 'nollsie',
 'nxthompson',
 'ocsmusic',
 'ofarevolution',
 'officialchrisa',
 'officialgreggallman',
 'officialindicud',
 'officialpoe',
 'officialrebeccaferguson',
 'officialwilanderson',
 'officialwolfmother',
 'old97s',
 'oleknyc',
 'oliverfisher_59',
 'oliviervernon54',
 'onemileatatime',
 'onestep4ward',
 'optimuscope',
 'ordinarytraveler',
 'orlyshani',
 'ottsworld',
 'ourawesomeplanet',
 'ourladypeace',
 'padraigharrington',
 'palila',
 'patrickcorbin46',
 'patrickkolts',
 'pattygmusic',
 'payphones',
 'petemurraymusic',
 'peteyorn',
 'pheebsfoods',
 'phildalhausser',
 'philgood50',
 'phillybrown10',
 'phillyglove',
 'philpressey',
 'pinka_makeup',
 'pinoyadventurista',
 'pissinginthepunchbowl',
 'plainwhitets',
 'pleasestayover',
 'plumdeluxe',
 'poemans_dream',
 'pommietravels',
 'pomobeats',
 'pre_occupations',
 'prinnie_stevens',
 'psimonmyway',
 'puertoricanbobby',
 'pysngr',
 'quincyacy',
 'rac',
 'rachaeleahcar',
 'rachaelyamagata',
 'radkeyrock',
 'raquelsofia',
 'rarariot',
 'rashadjohnson26',
 'raylandishere',
 'raymac3',
 'rayreed2',
 'realaimeemann',
 'realamyweber',
 'realdealrossyb',
 'realjrdonato',
 'realrickledo1',
 'rebeccajarvis',
 'rebeccarusch',
 'reecemastinofficial',
 'remikolawole',
 'repbarbaralee',
 'repjacksonlee',
 'repmarciafudge',
 'rezaphlv',
 'rhapsalazar',
 'rhondaburchmore',
 'rhysmillenracing',
 'ricardoallen_37',
 'richardengelnbc',
 'richardwilkins',
 'rileycooper_14',
 'rishardmatthews',
 'rizkyhanggono',
 ...]

In [11]:
accounts = pd.read_sql('select account, count(*) as n_posts from ins_account_data group by account'
                   ,con=connection_engine)
accounts

2022-04-06 05:15:36,884 INFO sqlalchemy.engine.Engine SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2022-04-06 05:15:36,885 INFO sqlalchemy.engine.Engine [cached since 24.62s ago] {'table_schema': 'instagram_data', 'table_name': 'select account, count(*) as n_posts from ins_account_data group by account'}
2022-04-06 05:15:36,924 INFO sqlalchemy.engine.Engine select account, count(*) as n_posts from ins_account_data group by account
2022-04-06 05:15:36,925 INFO sqlalchemy.engine.Engine [raw sql] {}

                            account  n_posts
0                  Rebecca Ferguson      234
1                    Angela Trimbur     1007
2                      Reza Pahlevi      917
3                   Danielle Guldin       22
4     Bret Lockett - Business Coach        7
...                             ...      ...
1261                    G                  1
1262     The Tube  In Black   White        2
1263                             JC        1
1264              Presidential Rell        1
1265                    Dental Diva        1

[1266 rows x 2 columns]